# docker-compose.yml

version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: spam_backend
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app
    # ewentualnie zmienne środowiskowe
    # environment:
    #   - DEBUG=1
    #   - ...
    # depends_on: [db]  # jeśli byłaby osobna baza

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spam_frontend
    ports:
      - "4200:8080"
    # jesli chcesz auto-odświeżanie, mount?
    # volumes:
    #   - ./frontend:/app

